### ISSUE TITLE
Add Partition Graph Support

### ISSUE THREAD

**Issue by platinummonkey** [platinummonkey/mogwai#10]
Make Partition Graph Support work with TP3 databases that support this. 

Also would providing an implementation for those that don't with partition property key-value pair on all vertices/edges be useful, or just fully disable this feature?

**Comment by aolieman** [comment]
As far as I can tell, the compatibility question is whether TP3 databases support [TraversalStrategy](http://tinkerpop.apache.org/docs/3.1.0-incubating/#traversalstrategy) in general. `PartitionStrategy` has no special requirements; rather progressive enhancement in the sense that the `partitionKey` may be hidden within the traversal if meta-properties are supported.

I'd like to contribute here, but am unsure which path to take. We could stick to the approach I used for TP2, which would be to use gremlin server sessions to persist the TraversalStrategy. I'm still unfamiliar with the new protocol client(s), however, so I don't know where it stands with session support. Also, the TP3 docs indicate some additional expense in the JVM when sessions are used.

I haven't given the alternatives much thought, but a naive sessionless approach would be to wrap each request in its own (identical) traversal strategy. Perhaps this communication overhead could be mitigated by somehow bundling queries within a traversal strategy context. Is there any transaction management capability in the protocol client that we could use?
