### ISSUE TITLE
Gremlin Query API for TP3

### ISSUE THREAD

**Issue by davebshow** [platinummonkey/mogwai#16]
Over the past couple weeks I've been working on #5 and #9, and I've made it to the query API tests. I was looking over the provided methods (steps), and was thinking that maybe they should be updated to reflect the new version Gremlin. Currently, you do something like this to get in vertices filtered by edge labels:

``` python
>>> jon.query().labels(EnrolledIn).direction(OUT).vertices()
```

In Gremlin, this query would look like this:

```
gremlin> g.V(jon).out('enrolledIn')
```

Therefore, I was thinking of implementing the new style Gremlin interface that provides the `vertex` steps [1], `has` steps [2], `value` and `valueMap` [3], as well as all of the predicates [4].

The resulting `mogwai` API would rewrite the previous query like such:

``` python
>>> yield jon.query().out(EnrolledIn).get()
```

And you could write a simple traversal as follows:

``` python
>>> yield v.query().outE(SomeEdgeType).inV().has("prop", (1, 5), INSIDE).valueMap().get()
```

Alternatively, we could loose the query method and do something like this:

``` python
>>> yield V(jon).out(EnrolledIn).get()

>>> yield V(v).outE(SomeEdgeType).inV().has("prop", (1, 5), INSIDE).valueMap().get()
```

Does anyone have any ideas or input about this? Should we use camelcase like Gremlin, or go the more pythonic route e.g. `value_map` instead of "valueMap"? @platinummonkey, @jsenecal - thoughts???
1. http://tinkerpop.apache.org/docs/3.1.0-incubating/#vertex-steps
2. http://tinkerpop.apache.org/docs/3.1.0-incubating/#has-step
3. http://tinkerpop.apache.org/docs/3.1.0-incubating/#valuemap-step
4. http://tinkerpop.apache.org/docs/3.1.0-incubating/#a-note-on-predicates

**Comment by jsenecal** [comment]
@davebshow I personally think it may be better to have the new syntax complemented (loosing the query method) some temporary method should be kept in here to facilitate people coming from pre-tp3 versions to upgrade. This method should show a deprecation notice while working as usual.

**Comment by jsenecal** [comment]
Also, regarding your question, the methods should be kept as pythonic as possible... IMO

**Comment by davebshow** [comment]
@jsenecal Regarding the temporary method/deprecation notice, you think this is necessary? All of these changes are API breaking and backward compatibility is not a possibility with the TP3 upgrade.

**Comment by jsenecal** [comment]
@davebshow yeah - I kinda thought about this afterwards but forgot to come back to it... No, you are right, all these are breaking changes.

**Comment by davebshow** [comment]
If there is no more feedback I will go ahead and close this issue.
