### ISSUE TITLE
rexrpo version is broken in Setup.py

### ISSUE THREAD

**Issue by dmitrytokarev** [platinummonkey/mogwai#2]
see https://github.com/platinummonkey/mogwai/blob/master/setup.py#L67
so released version https://pypi.python.org/pypi/mogwai/0.7.6 is broken

**Comment by dmitrytokarev** [comment]
opened https://github.com/platinummonkey/mogwai/pull/3 to fix this

**Comment by platinummonkey** [comment]
0.7.7 released!  Thanks for catching this!
