### ISSUE TITLE
RexProScriptException transaction is not open in Django with Titan 

### ISSUE THREAD

**Issue by blackboxx** [platinummonkey/mogwai#4]
Hello Mogwai team. I have stuck with my TitanDB and Django 1.8 Mogwai 0.7.7 package. I have Graph database titan/cassandra on localhost dev machine, and after creating wrong queries in rexster gremlin web interface my Django Object Graph Mapper mogwai stopped to work. Titan is still working and data are present but Django stopped to work with it. Here is my Stackoverflow question.
http://stackoverflow.com/questions/33975524/rexproscriptexception-transaction-is-not-open-in-django-with-titan-graph-db

**Comment by platinummonkey** [comment]
hm, 0.7.7 includes that fix and a couple more we've found. Can you post of a repeatable example where I can create a test case around this? thanks!
