### ISSUE TITLE
Replace RexPro Connector with Gremlin-Server compatible library

### ISSUE THREAD

**Issue by platinummonkey** [platinummonkey/mogwai#6]
In order to talk to Gremlin-Server we'll need to replace the current rexpro-python implementation with a Gremlin-Server compatible library. @davebshow has done a good amount of work here, we just need to finish the integration with mogwai.

Long term ideally also make this plug-able for other communication libraries (ie a HTTP library, or <future> library) and support asynchronous streaming of responses, but we can hold off for M2/M3/GA.

**Comment by jsenecal** [comment]
Like @davebshow mentionned in https://github.com/platinummonkey/mogwai/issues/1#issuecomment-161392947, it seems like this had been done already in the thinkerpop3 branch... see https://github.com/platinummonkey/mogwai/commit/3ebb9e86881a8a9f658c03d2407862edb227edc4

Or maybe I am missing something ?

**Comment by platinummonkey** [comment]
Yeah, there is some work already started down this path, the tests definitely need updating as they are currently failing.  You are correct, the "tinkerpop3" branch is where this work has begun.
